### ISSUE TITLE
Error during scanning https target.

### ISSUE THREAD

**Issue by gvv90** [greenbone/gvm#102]
I'm trying to scan an https target protected by Datapower. The .cert and .key files were generated inside Datapower and the pkcs file, was generated with openssl. Can you tell me how may I import the pkcs12 file in command line please? version:Openvas 9 so:Fedora24

**Comment by cfi-gb** [comment]
@gvv90 Please note the following:

3. be aware that this is not a support forum. If your issue is more a question than a bug report, please check http://openvas.org/ for available support options.

which is explained in the issue template showing up when creating a new issue.

**Comment by timopollmeier** [comment]
I agree that this should have been asked in a place like the OpenVAS mailing lists first, so I'm closing this issue. If it turns out that new functionality is needed for scanning your targets, you should probably ask the NVT developers.
