### ISSUE TITLE
How to connect OpenVAS manager to remote PgSQL server?

### ISSUE THREAD

**Issue by Bosco-Lam** [greenbone/gvm#109]
Now I can connect OpenVAS manager to local PgSQL server.
But now I want to connect remote PgSQL server.
Then I change the file src/sql_pg.c, In line 267 "dbname=%s user=xxx password=xxx hostaddr=x.x.x.x port=5432".
But it cannot be setup successfully, what can I do now?

**Comment by bjoernricks** [comment]
This is not a support forum.

From our issue template:

> 3. be aware that this is not a support forum. If your issue is more a question
>    than a bug report, please check http://openvas.org/ for available support
>    options.

**Comment by Bosco-Lam** [comment]
@bjoernricks I don't need any support. Maybe you can just tell me can openvas manager connect to remote PgSQL server? Just yes or no. I can research it by myself

**Comment by bjoernricks** [comment]
@Bosco-Lam you are asking for something. That's not a bug nor a feature request. Actually that **IS** asking for support. Please use the mailing lists for such questions http://www.openvas.org/mail.html.

Don't get my reply as an offense. We have to keep the communication channels clean and consistent.
