### ISSUE TITLE
Hi I have an issue running Openvas scanner and the error is Openvas scanner is not working it shows an fix to run openvassd but I'm unable to run it. please recommend what to do on this

### ISSUE THREAD

**Issue by dsvsdheeraj** [greenbone/gvm#169]
### Steps to reproduce
1.
2.
3.

### GVM versions
**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```

```

**Comment by janowagner** [comment]
Unfortunately, the bug report lacks any details to help understand how to reproduce etc.

Also, from the lengthly title I gather that the problem is about "openvas-scanner" and not "gvm" (where
it is reported for).

So I close right away.
