### ISSUE TITLE
[7.0.2] When an task is requestet an sql error will be show

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvm#17]
I simple add an IP as an scan target and let the "System Discovery" scan run.

> d manage:   INFO:2018-02-09 05h56.30 UTC:22201: nvt_selector_plugins: NVTs not explicitly activated anymore for this config: 1.3.6.1.4.1.25623.1.0.10265;1.3.6.1.4.1.25623.1.0.103914;1.3.6.1.4.1.25623.1.0.103978
> ;1.3.6.1.4.1.25623.1.0.95888;1.3.6.1.4.1.25623.1.0.12241;1.3.6.1.4.1.25623.1.0.108298;1.3.6.1.4.1.25623.1.0.11933;1.3.6.1.4.1.25623.1.0.12288;1.3.6.1.4.1.25623.1.0.80010;1.3.6.1.4.1.25623.1.0.810010;1.3.6.1.4.1.
> 25623.1.0.10870;1.3.6.1.4.1.25623.1.0.108215;1.3.6.1.4.1.25623.1.0.80011;1.3.6.1.4.1.25623.1.0.103585;1.3.6.1.4.1.25623.1.0.103697;1.3.6.1.4.1.25623.1.0.100509;1.3.6.1.4.1.25623.1.0.80104;1.3.6.1.4.1.25623.1.0.8
> 0086;1.3.6.1.4.1.25623.1.0.900238;. Please adjust the config if you think this is wrong.
> md manage:WARNING:2018-02-09 05h56.31 UTC:22201: sql_prepare_internal: sqlite3_prepare failed: near "(": syntax error
> md manage:WARNING:2018-02-09 05h56.31 UTC:22201: init_iterator: sql_prepare failed
> md manage:WARNING:2018-02-09 05h56.31 UTC:22201: manage_cleanup_process_error: Error exit, setting running task to Internal Error
> md manage:WARNING:2018-02-09 05h56.31 UTC:22201: sql_prepare_internal: sqlite3_prepare failed: near "(": syntax error
> md manage:WARNING:2018-02-09 05h56.31 UTC:22201: init_iterator: sql_prepare failed
>

**Comment by cfi-gb** [comment]
@tuxmaster You need sqlite3 >= 3.8.3 on your system. Current trunk is checking for these requirements with the following commits:

https://github.com/greenbone/gvm/commit/d20518948fa32bdd9a698c3bedb1dad4fb225b99
https://github.com/greenbone/gvm/commit/f0448207b1c08bcc16f23180b64932ef5d626155

**Comment by tuxmaster** [comment]
Yes it will fix it.

**Comment by fcolista** [comment]
Seems there is a regression of this bug with openvas 10.
The OS is Alpine Linux (runs on musl libc) edge version on x86_64
I get these errors when I start a task on gsad:
```
md manage:WARNING:2019-04-09 19h36.51 UTC:2469: sql_prepare_internal: sqlite3_prepare failed: not an error
md manage:WARNING:2019-04-09 19h36.51 UTC:2469: init_iterator: sql_prepare failed
```
This happens with the following packages installed:
```
sqlite-3.27.2
gvm-libs-10.0.0
gvmd-8.0.0
openvas-scanner-6.0.0
greenbone-security-assistant-8.0.0
```

What I've noticed (perhaps is linked to this problem), is that importing the nvt i got tons of these WARNING:
```
md manage:WARNING:2019-04-09 19h27.24 utc:1035: parse_ctime: Failed to parse time '2018-02-27T19:15:33.110Z'
```
Please note that Alpine doesn't use /etc/TZ to set local time, rather [tzdata](https://www.iana.org/time-zones)

I've not tested with PostgreSQL as yet. 
BTW, appears to be impossible to build gvmd supporting both postgres and sqlite...
Please let me know what else I can do for testing, thanks.
.: Francesco

**Comment by fcolista** [comment]
Small update.
Seems that somehow I'm hitting a limit:
```
md manage:WARNING:2019-04-09 19h59.02 UTC:4052: sql_prepare_internal: sqlite3_prepare failed: no more rows available
md manage:WARNING:2019-04-09 19h59.02 UTC:4052: sql_x_internal: sql_prepare failed
md manage:WARNING:2019-04-09 19h59.02 UTC:4052: sql_close: attempt to close db with open statement(s)
```
No more rows available.
But this is impossible, since the limit is 140Terabyte and  SQLite documentation states:
```
Maximum Number Of Rows In A Table

The theoretical maximum number of rows in a table is 264 (18446744073709551616 or about 1.8e+19). This limit is unreachable since the maximum database size of 140 terabytes will be reached first. A 140 terabytes database can hold no more than approximately 1e+13 rows, and then only if there are no indices and if each row contains very little data.
```
SQlite on Alpine is built with the following options:
```
-DSQLITE_ENABLE_FTS4 \
	-DSQLITE_ENABLE_FTS3_PARENTHESIS \
	-DSQLITE_ENABLE_FTS3 \
	-DSQLITE_ENABLE_FTS5 \
	-DSQLITE_ENABLE_COLUMN_METADATA \
	-DSQLITE_SECURE_DELETE \
	-DSQLITE_ENABLE_UNLOCK_NOTIFY \
	-DSQLITE_ENABLE_RTREE \
	-DSQLITE_ENABLE_GEOPOLY \
	-DSQLITE_USE_URI \
	-DSQLITE_ENABLE_DBSTAT_VTAB \
	-DSQLITE_MAX_VARIABLE_NUMBER=250000 \
	-DSQLITE_ENABLE_JSON1"
```

.: Francesco

**Comment by cfi-gb** [comment]
@fcolista Thanks for your report. Please open a new issue here at this issue tracker as your problem is unrelated to this discussed issue:

The initial report was about the host system of the OP not providing a recent SQLite version (>= 3.8.3) and wasn't a bug in openvasmd/gvmd but a packaging issue.
