### ISSUE TITLE
Failed to start Open Vulnerability Assessment System Scanner Demon

### ISSUE THREAD

**Issue by KevinBollengier** [greenbone/gvm#195]
### Expected behavior
Scanner services booting when openvas-start is entered in the terminal.
### Current behavior
The service doesn't start and thus scanning isn't possible.
### Steps to reproduce
1.
2.
3.

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 7.0.3

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.3
**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**
Kali Linux
**Installation method / source:** (packages, source installation)
apt-get install openvas
### Logfiles

```
No logs found
```

**Comment by cfi-gb** [comment]
@KevinBollengier Note the following in the used template:

> 3. be aware that this is not a support forum. If your issue is more a question
   than a bug report, please use https://community.greenbone.net/c/gse instead.

**NOTE:** This is generally valid for nearly every project using the github issue trackers. Only use those for bug reports and the mailing lists / forums for support questions.

Please close here and use the mentioned community portal for your support request. Thanks for your help to keep the communication channels clean and consistent.

As a side note you're issues is most likely from your systemd files of Kali having a too lower timeout for the startup of the scanner or your environment has an insufficient Redis setup/configuration:

https://community.greenbone.net/t/hint-redis-setup-configuration-for-gse-gvm-openvas/333
