### ISSUE TITLE
"(Perhaps the db went down?)"

### ISSUE THREAD

**Issue by asmaack** [greenbone/gvm#199]
### Expected behavior
Normal openvas scans to finish.

### Current behavior
Normal openvas scan is created and started through "gvm-cli socket" commands with <create_target>, <create_task>, <start_task>. 

Then, sometimes, the scan will halt/freeze and gvm-cli cannot even authenticate to openvasmd and the openvasmd.log will spew out errors endlessly (see below).

The openvassd is stuck (**always at host_details.nasl**):

`19866 ?        SN     0:00  |       \_ openvassd: testing x.x.x.x (/usr/local/var/lib/openvas/plugins/2011/host_details.nasl)
`

gvm-cli socket -c --xml "<get_version/>" (and all other "gvm-cli socket" commands)  will respond with errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/gvm-cli", line 11, in <module>
    load_entry_point('gvm-tools==1.4.1', 'console_scripts', 'gvm-cli')()
  File "/usr/local/lib/python3.6/dist-packages/gmp/clients/gvm_cli.py", line 212, in main
    gvm.authenticate(args.gmp_username, args.gmp_password)
  File "/usr/local/lib/python3.6/dist-packages/gmp/gvm_connection.py", line 220, in authenticate
    return self.read()
  File "/usr/local/lib/python3.6/dist-packages/gmp/gvm_connection.py", line 103, in read
    response = self.readAll()
  File "/usr/local/lib/python3.6/dist-packages/gmp/gvm_connection.py", line 967, in readAll
    data = self.sock.recv(BUF_SIZE)
ConnectionResetError: [Errno 104] Connection reset by peer
```

The only resolution seems to be to restart openvasmd and openvassd, or restart the server platform, by which of course the scan is trashed and must be repeated.

Restarting the redis-server by itself has no effect.

### GVM versions
**gsa:** (gsad --version)
Not in use.

**gvm:** (gvmd --version)
~$ openvasmd --version
OpenVAS Manager 7.0.4
GIT revision 1bbda358-openvas-manager-7.0
Manager DB revision 184

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.3

**gvm-libs:**
~/gvm-libs$ git log
commit db1306c117df6dde5324b75cb4517b2382a5ba98 (HEAD -> openvas-libraries-9.0, origin/openvas-libraries-9.0)

**openvas-smb:**

### Environment
**Operating system:**
$ uname -a
Linux xxx 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source:** 
(source installation)

### Logfiles
/usr/local/var/log/openvas/openvasmd.log repeats the following over and over again:
```
md manage:WARNING:2018-10-04 14h48.40 utc:17917: sql_exec_internal: sqlite3_step failed: cannot start a transaction within a transaction
md manage:WARNING:2018-10-04 14h48.40 utc:17917: sqlv: sql_exec_internal failed
md manage:WARNING:2018-10-04 14h48.40 utc:17917: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2018-10-04 14h48.41 utc:22606: sql_exec_internal: sqlite3_step failed: interrupted
md manage:WARNING:2018-10-04 14h48.41 utc:22606: sqlv: sql_exec_internal failed
...
```

**Comment by asmaack** [comment]
It turns out we were using gsad (master branch) with the openvasmd (release branch), while communicating with openvasmd through gvm-cli xml commands.
A sure way to reproduce this problem is to do just that!

I Suppose this is not a valid usecase, since the master branch should not go with the release brances?

**Comment by bjoernricks** [comment]
gsad master should never talk with openvasmd.It may work for many commands but [gmp](https://community.greenbone.net/t/about-the-greenbone-management-protocol-gmp-category/83) has been changed and therefore gsad master isn't compatible with openvasmd anymore.
