### ISSUE TITLE
[7.0.2] no ip will logged when log in with in invalid user/wrong pasword

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvm#25]
When try to login with in invalid user or password then in the log file only the dummy value is logged as the source ip.

> md    omp:WARNING:2018-03-06 08h38.20 utc:1876: Authentication failure for 'inavlid' from 900::900:0:0:0

Config for the log:
```
[md    omp]
prepend=%t %p
prepend_time_format=%Y-%m-%d %Hh%M.%S %Z
file=/var/log/openvas/openvasmd.log
level=16
```

**Comment by cfi-gb** [comment]
Should be fixed when rebuilding the Manager against the recent release of the libs https://github.com/greenbone/gvm-libs/releases/tag/v9.0.2:

```
md    omp:WARNING:2018-03-12 20h56.30 utc:8485: Authentication failure for 'admin' from unix_socket
md    omp:WARNING:2018-03-12 20h56.33 utc:8493: Authentication failure for 'admin' from unix_socket
```

**Comment by tuxmaster** [comment]
Yes, it will fix it. Now the log will show:
==> /var/log/openvas/openvasmd.log <==
md    omp:WARNING:2018-03-21 09h13.22 utc:27707: Authentication failure for 'fghfghfgh' from unix_socket
