### ISSUE TITLE
OpenVAS fails to rebuild database after a clean install

### ISSUE THREAD

**Issue by shibumi** [greenbone/gvm#98]
### Expected behavior
`openvasmd --rebuild --progress` should work as expected.

### Current behavior
Rebuilding the database is failing or hanging. See also: https://bugs.archlinux.org/task/57470

### Steps to reproduce
1. Install openvas-manager from Arch Linux repositories
2. execute `openvasamd --rebuild --progress`
3. wait for it

### GVM versions
**gsa:** 7.0.3

**gvm:** 7.0.3

**openvas-scanner:** 5.1.2

**gvm-libs:** 9.0.2

### Environment
**Operating system:** Arch Linux

**Installation method / source:** package installation

Here is the way I build gvm:
```
sed -i '1c#!/usr/bin/python2' tools/extra/xml_split
cmake -DCMAKE_BUILD_TYPE=Release -DSBINDIR=/usr/bin \
    -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONFDIR=/etc -DLOCALSTATEDIR=/var .
make
make install
```

### Logfiles

```
Sorry no log files provided. But if you tell me what you need I try to start a container or VM and get it.
```

**Comment by cfi-gb** [comment]
@shibumi This sounds to me more like a setup issue which should go to http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss

e.g. the Wiki Article on Arch https://wiki.archlinux.org/index.php/OpenVAS says to setup the OpenVAS related redis stuff "Post-install":

https://wiki.archlinux.org/index.php/OpenVAS#Post-install

but this needs to be done before the initial start of openvassd

**Comment by cfi-gb** [comment]
As a side note also make sure to apply the recommended settings shown in https://github.com/greenbone/openvas-scanner/pull/93

Especially the commented out "save" statements are important and might be the root cause of this issue if missing.

**Comment by salsa-dev** [comment]
I've also bumped into this on Ubuntu 16.04.
Rebuild process was hanging on generating certificate. This was due to low entropy.
Try to increase kernel entropy for GPG key generation during 'openvasmd --rebuild' install package 'haveged'
